// Copyright Jamie Iles, 2018
//
// This file is part of s80x86.
//
// AUTO-GENERATED by generate_insn_decoder_helpers.py
// Do not edit manually!

function logic insn_has_modrm;
    input logic [7:0] opcode;

    casez (opcode)
    8'h3f: insn_has_modrm = 1'b1;
    8'h62: insn_has_modrm = 1'b1;
    8'h69: insn_has_modrm = 1'b1;
    8'h6b: insn_has_modrm = 1'b1;
    8'h80: insn_has_modrm = 1'b1;
    8'h81: insn_has_modrm = 1'b1;
    8'h82: insn_has_modrm = 1'b1;
    8'h83: insn_has_modrm = 1'b1;
    8'h86: insn_has_modrm = 1'b1;
    8'h87: insn_has_modrm = 1'b1;
    8'h88: insn_has_modrm = 1'b1;
    8'h89: insn_has_modrm = 1'b1;
    8'h8a: insn_has_modrm = 1'b1;
    8'h8b: insn_has_modrm = 1'b1;
    8'h8c: insn_has_modrm = 1'b1;
    8'h8d: insn_has_modrm = 1'b1;
    8'h8e: insn_has_modrm = 1'b1;
    8'h8f: insn_has_modrm = 1'b1;
    8'h9d: insn_has_modrm = 1'b1;
    8'ha7: insn_has_modrm = 1'b1;
    8'haf: insn_has_modrm = 1'b1;
    8'hc0: insn_has_modrm = 1'b1;
    8'hc1: insn_has_modrm = 1'b1;
    8'hc4: insn_has_modrm = 1'b1;
    8'hc5: insn_has_modrm = 1'b1;
    8'hc6: insn_has_modrm = 1'b1;
    8'hc7: insn_has_modrm = 1'b1;
    8'hd0: insn_has_modrm = 1'b1;
    8'hd1: insn_has_modrm = 1'b1;
    8'hd2: insn_has_modrm = 1'b1;
    8'hd3: insn_has_modrm = 1'b1;
    8'hd4: insn_has_modrm = 1'b1;
    8'hd9: insn_has_modrm = 1'b1;
    8'hdd: insn_has_modrm = 1'b1;
    8'hdf: insn_has_modrm = 1'b1;
    8'hf6: insn_has_modrm = 1'b1;
    8'hf7: insn_has_modrm = 1'b1;
    8'hfe: insn_has_modrm = 1'b1;
    8'hff: insn_has_modrm = 1'b1;
    default: insn_has_modrm = 1'b0;
    endcase
endfunction

function logic [1:0] insn_immed_count;
    input logic [7:0] opcode;
    input logic [2:0] modrm_reg;

    unique casez ({opcode, modrm_reg})
    {8'h3f, 3'b???}: insn_immed_count = 2'd1;
    {8'h54, 3'b???}: insn_immed_count = 2'd1;
    {8'h60, 3'b???}: insn_immed_count = 2'd1;
    {8'h61, 3'b???}: insn_immed_count = 2'd1;
    {8'h62, 3'b???}: insn_immed_count = 2'd1;
    {8'h68, 3'b???}: insn_immed_count = 2'd1;
    {8'h69, 3'b???}: insn_immed_count = 2'd1;
    {8'h6a, 3'b???}: insn_immed_count = 2'd1;
    {8'h6b, 3'b???}: insn_immed_count = 2'd1;
    {8'h6c, 3'b???}: insn_immed_count = 2'd1;
    {8'h6d, 3'b???}: insn_immed_count = 2'd1;
    {8'h6e, 3'b???}: insn_immed_count = 2'd1;
    {8'h6f, 3'b???}: insn_immed_count = 2'd1;
    {8'h98, 3'b???}: insn_immed_count = 2'd1;
    {8'h99, 3'b???}: insn_immed_count = 2'd1;
    {8'h9a, 3'b???}: insn_immed_count = 2'd1;
    {8'h9c, 3'b???}: insn_immed_count = 2'd1;
    {8'h9d, 3'b???}: insn_immed_count = 2'd1;
    {8'ha0, 3'b???}: insn_immed_count = 2'd1;
    {8'ha1, 3'b???}: insn_immed_count = 2'd1;
    {8'ha2, 3'b???}: insn_immed_count = 2'd1;
    {8'ha3, 3'b???}: insn_immed_count = 2'd1;
    {8'ha4, 3'b???}: insn_immed_count = 2'd1;
    {8'ha5, 3'b???}: insn_immed_count = 2'd1;
    {8'ha6, 3'b???}: insn_immed_count = 2'd1;
    {8'ha7, 3'b???}: insn_immed_count = 2'd1;
    {8'haa, 3'b???}: insn_immed_count = 2'd1;
    {8'hab, 3'b???}: insn_immed_count = 2'd1;
    {8'hac, 3'b???}: insn_immed_count = 2'd1;
    {8'had, 3'b???}: insn_immed_count = 2'd1;
    {8'hae, 3'b???}: insn_immed_count = 2'd1;
    {8'haf, 3'b???}: insn_immed_count = 2'd1;
    {8'hc0, 3'b???}: insn_immed_count = 2'd1;
    {8'hc1, 3'b???}: insn_immed_count = 2'd1;
    {8'hc2, 3'b???}: insn_immed_count = 2'd1;
    {8'hc3, 3'b???}: insn_immed_count = 2'd1;
    {8'hc4, 3'b???}: insn_immed_count = 2'd1;
    {8'hc5, 3'b???}: insn_immed_count = 2'd1;
    {8'hc7, 3'b???}: insn_immed_count = 2'd1;
    {8'hc8, 3'b???}: insn_immed_count = 2'd1;
    {8'hc9, 3'b???}: insn_immed_count = 2'd1;
    {8'hca, 3'b???}: insn_immed_count = 2'd1;
    {8'hcb, 3'b???}: insn_immed_count = 2'd1;
    {8'hcc, 3'b???}: insn_immed_count = 2'd1;
    {8'hcd, 3'b???}: insn_immed_count = 2'd1;
    {8'hce, 3'b???}: insn_immed_count = 2'd1;
    {8'hcf, 3'b???}: insn_immed_count = 2'd1;
    {8'hd4, 3'b???}: insn_immed_count = 2'd1;
    {8'hd5, 3'b???}: insn_immed_count = 2'd1;
    {8'hdf, 3'b???}: insn_immed_count = 2'd1;
    {8'he0, 3'b???}: insn_immed_count = 2'd1;
    {8'he1, 3'b???}: insn_immed_count = 2'd1;
    {8'he2, 3'b???}: insn_immed_count = 2'd1;
    {8'he3, 3'b???}: insn_immed_count = 2'd1;
    {8'he4, 3'b???}: insn_immed_count = 2'd1;
    {8'he5, 3'b???}: insn_immed_count = 2'd1;
    {8'he6, 3'b???}: insn_immed_count = 2'd1;
    {8'he7, 3'b???}: insn_immed_count = 2'd1;
    {8'he8, 3'b???}: insn_immed_count = 2'd1;
    {8'he9, 3'b???}: insn_immed_count = 2'd1;
    {8'hea, 3'b???}: insn_immed_count = 2'd1;
    {8'heb, 3'b???}: insn_immed_count = 2'd1;
    {8'hf8, 3'b???}: insn_immed_count = 2'd1;
    {8'hf9, 3'b???}: insn_immed_count = 2'd1;
    {8'hfa, 3'b???}: insn_immed_count = 2'd1;
    {8'hfb, 3'b???}: insn_immed_count = 2'd1;
    {8'hfc, 3'b???}: insn_immed_count = 2'd1;
    {8'hfd, 3'b???}: insn_immed_count = 2'd1;
    {8'hfe, 3'b???}: insn_immed_count = 2'd1;
    default: insn_immed_count = 2'b0;
    endcase
endfunction

function logic insn_immed_is_8bit;
    input logic [7:0] opcode;
    input logic [2:0] modrm_reg;
    input logic immed_num;

    unique casez ({opcode, modrm_reg})
    {8'h3f, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h54, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h60, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h61, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h62, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h68, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h69, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h6a, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h6b, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h6c, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h6d, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h6e, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h6f, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h98, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h99, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h9a, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h9c, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'h9d, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha0, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha1, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha2, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha3, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha4, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha5, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha6, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'ha7, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'haa, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hab, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hac, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'had, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hae, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'haf, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc0, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc1, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc2, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc3, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc4, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc5, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc7, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc8, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hc9, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hca, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hcb, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hcc, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hcd, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hce, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hcf, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hd4, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hd5, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hdf, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he0, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he1, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he2, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he3, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he4, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he5, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he6, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he7, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he8, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'he9, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hea, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'heb, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hf8, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hf9, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hfa, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hfb, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hfc, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hfd, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    {8'hfe, 3'b???}: insn_immed_is_8bit = ~|(2'b01 & (2'b1 << immed_num));
    default: insn_immed_is_8bit = 1'b0;
    endcase
endfunction
